services:
    #######################################################
    #  img-shifter
    #######################################################
  img-shifter:
    build:
      context: .
      dockerfile: ./apps/img-shifter/Dockerfile
      target: development
    # command: pnpm run start:dev img-shifter
    # env_file:
    #   - ./apps/img-shifter/.env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
