services:
  #######################################################
  #  gateway
  #######################################################
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    command: bun dist/gateway/index.js
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network
      - minio_network
  #######################################################
  #  img-shifter
  #######################################################
  img-shifter:
    build:
      context: .
      dockerfile: ./apps/img-shifter/Dockerfile
    command: node apps/img-shifter/dist/main.js
    # env_file:
    #   - ./apps/img-shifter/.env
    ports:
      - 3001:3001
    networks:
      - rabbitmq_network
      - minio_network
  #######################################################
  #  rabbitmq
  #######################################################
  rabbitmq:
    image: rabbitmq:3.13.6-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network
    restart: unless-stopped
  minio:
    build:
      context: ./docker-compose/minio
      dockerfile: Dockerfile
    container_name: minio
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - ./minio_data:/data
    networks:
      - minio_network

networks:
  rabbitmq_network:
    driver: bridge
  minio_network:
    driver: bridge
