services:
  #######################################################
  #  gateway
  #######################################################
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: node dist/apps/gateway/index.js
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    #######################################################
    #  img-shifter
    #######################################################
  img-shifter:
    build:
      context: .
      dockerfile: ./apps/img-shifter/Dockerfile
      target: development
    command: node dist/apps/img-shifter/index.js
    # env_file:
    #   - ./apps/img-shifter/.env
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
  #######################################################
  #  rabbitmq
  #######################################################
  rabbitmq:
    image: rabbitmq:3.13.6
    ports:
      - 5672:5672
      - 15672:15672
