services:
  #######################################################
  #  gateway
  #######################################################
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    command: bun dist/gateway/index.js
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    #######################################################
    #  img-shifter
    #######################################################
    networks:
      - rabbitmq_network
  img-shifter:
    build:
      context: .
      dockerfile: ./apps/img-shifter/Dockerfile
    command: node apps/img-shifter/dist/main.js
    # env_file:
    #   - ./apps/img-shifter/.env
    ports:
      - 3001:3001
    networks:
      - rabbitmq_network
  #######################################################
  #  rabbitmq
  #######################################################
  rabbitmq:
    image: rabbitmq:3.13.6-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network
    restart: unless-stopped

networks:
  rabbitmq_network:
    driver: bridge
