# services:
#     #######################################################
#     #  img-shifter
#     #######################################################
#   img-shifter:
#     tty: true
#     build:
#       context: .
#       dockerfile: ./apps/img-shifter/Dockerfile
#       target: development
#     # command: pnpm run img:dev
#     commnand: node dist/apps/img-shifter/index
#     # command: pnpm img:dev
#     #   - ./apps/img-shifter/.env
#     ports:
#       - 3000:3000
#     volumes:
#       - .:/usr/src/app
version: '3.8'

services:
  img-shifter:
    tty: true
    build:
      context: .
      dockerfile: ./apps/img-shifter/Dockerfile
      target: production
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app:ro  # Ensure read-only to avoid overwriting
    command: node dist/apps/img-shifter/index
    environment:
      NODE_ENV: production

